spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.178.244.31/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 20010119

server:
  port: 8181