spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://175.178.244.31/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 20010119
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB

server:
  port: 8181


#控制台打印sql
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/ling/mapper/*.xml



